/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColumnChart: typeof import('./src/components/ColumnChart.vue')['default']
    IndicatorCard: typeof import('./src/components/IndicatorCard.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    OTModal: typeof import('./src/components/OTModal.vue')['default']
    OTPagination: typeof import('./src/components/OTPagination.vue')['default']
    OTTable: typeof import('./src/components/OTTable.vue')['default']
    OTText: typeof import('./src/components/OTText.vue')['default']
    OTTooltip: typeof import('./src/components/OTTooltip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
